// Package history provides a thread-safe circular buffer for recording
// port-check events generated by portwatch.
//
// # Overview
//
// The [Ring] type stores [Entry] values in a fixed-size buffer, automatically
// overwriting the oldest entries when capacity is exceeded. This keeps memory
// usage bounded regardless of how long the daemon runs.
//
// The [Recorder] type wraps a Ring and integrates directly with
// [portwatch/internal/checker] status values, converting them to human-readable
// strings before storage.
//
// # Usage
//
//	rec := history.NewRecorder(200)
//	rec.Record("api-gateway", "10.0.0.5", 8080, checker.StatusDown)
//	for _, e := range rec.Entries() {
//		fmt.Printf("%s %s:%d %s\n", e.Timestamp.Format(time.RFC3339), e.Host, e.Port, e.Status)
//	}
package history
